### ISSUE TITLE
Charging information

### ISSUE THREAD

**Issue by eaglemao** [debuggerx01/battery_indicator#1]
If the battery is charging, is there any way to show the information through the battery indicator? Thanks!

**Comment by debuggerx01** [comment]
No, but you can do like this:
![20200310160159](https://user-images.githubusercontent.com/19624835/76291935-1bb57400-62e9-11ea-82bd-d72718fb79a6.gif)

[https://gist.github.com/debuggerx01/ebe120a29a06341665d339c45fddc42b](https://gist.github.com/debuggerx01/ebe120a29a06341665d339c45fddc42b)
