### ISSUE TITLE
Upgrade  from battery_plus ^2.0.1 to ^3.0.2

### ISSUE THREAD

**Issue by kekko7072** [debuggerx01/battery_indicator#12]
Pleas update the package dependencies.
```
Because battery_indicator 0.1.1 depends on battery_plus ^2.0.1 and no versions of battery_indicator match >0.1.1 <0.2.0, battery_indicator ^0.1.1 requires battery_plus ^2.0.1.
So, because app depends on both battery_plus ^3.0.2 and battery_indicator ^0.1.1, version solving failed.
pub get failed (1; So, because app depends on both battery_plus ^3.0.2 and battery_indicator ^0.1.1, version solving failed.)
```

**Comment by debuggerx01** [comment]
> Pleas update the package dependencies.
> 
> ```
> Because battery_indicator 0.1.1 depends on battery_plus ^2.0.1 and no versions of battery_indicator match >0.1.1 <0.2.0, battery_indicator ^0.1.1 requires battery_plus ^2.0.1.
> So, because app depends on both battery_plus ^3.0.2 and battery_indicator ^0.1.1, version solving failed.
> pub get failed (1; So, because app depends on both battery_plus ^3.0.2 and battery_indicator ^0.1.1, version solving failed.)
> ```

Upgraded.

**Comment by kekko7072** [comment]
Thank you so much
