### ISSUE TITLE
Suggested Improvement

### ISSUE THREAD

**Issue by hoseyneil** [debuggerx01/battery_indicator#6]
When you try make the battery size bigger than 20, the font size (where you do widget.size -2) doesn't work too well.  I think allowing to pass in a property to set the font size would be nice.  Default it to 90% of the size value.

**Comment by debuggerx01** [comment]
new version published, pls try~

**Comment by hoseyneil** [comment]
Sorry i was going to add a PR but just didnt have time yet!  Thanks for doing it, if you ever need help let me know!
