### ISSUE TITLE
cannot change battery percentage

### ISSUE THREAD

**Issue by nuwanuom18** [debuggerx01/battery_indicator#7]

**Comment by WilliBobadilla** [comment]
what state manager are you using? I did something with GetX, I can share with you if you want

**Comment by nuwanuom18** [comment]
Sure.

**Comment by WilliBobadilla** [comment]
I uploaded to my repo, you can check it https://github.com/WilliBobadilla/custom_battery_indicator

**Comment by WilliBobadilla** [comment]
check this new repo forked from the original source: https://github.com/WilliBobadilla/battery_indicator/tree/dev_custom_battery_level

**Comment by debuggerx01** [comment]
The new version has been released, thanks to @WilliBobadilla :laughing:
